version: '3.1'

services:
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - tfb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  tfb_data:
